const languageText = {
    'create_title': "Tạo dự án mới",
    'name_title': "Tên dự án",
    'place_title': "Nhập tên dự án",
    'desc_project': "Mô tả dự án",
    'start_date': "Ngày bắt đầu",
    'place_start': "Chọn thời gian bắt đầu",
    'end_date': "Ngày kết thúc",
    'place_end': "Chọn thời gian kết thúc",
    'add_image': "Thêm hình ảnh",
    'name_button_create': "Tạo mới",
    'edit_project': "Chỉnh sửa dự án",
    'delete_project': "Xóa dự án",
    'desc_delete_project': "Xóa dự án",
    'edit': "Sửa",
    'delete': "Xóa",
    'title_all_project': 'Tất cả dự án',
    'confirm_delete_project': 'Bạn bạn muốn xóa dự án',
    'content_text':'Nội dung',
    'image_text':'Hình ảnh',
    'progress_text':'Tiến độ dự án',
    'status_text':'Trạng thái',
    'action_text':'Hoạt động',
    'search_text':'Tìm kiếm',
    'next_page_text':'Trang trước',
    'previous_page_text':'Trang sau',
    'first_page_text':'Trang Đầu',
    'last_page_text':'Trang Cuối',
    'choose_center':'Chọn Trung tâm',
    'choose_code':'Chọn mã dự án',
    'create_code':'Tạo mã dự án',
    'remove_img':'Xóa hình ảnh',
    'create_success':'Bạn đã tạo dự án thành công',
    'edit_success':'Bạn đã sửa dự án thành công',
    'pending':'Đang chờ xử lý',
    'title_remove_project':'Bạn có muốn xóa dự án?',
    'cancel_text':'Hủy',
    'remove_text':'Xóa',
    'success_remove_project':'Bạn đã xóa dự án thành công',
}
export { languageText };